# Generated by Django 5.0.4 on 2024-04-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='vrai_faux',
            new_name='isTheResponse',
        ),
        migrations.RenameField(
            model_name='reponse',
            old_name='reponse',
            new_name='response',
        ),
    ]
