# Generated by Django 3.1.7 on 2024-04-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_alter_matchmeking_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmeking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
