# Generated by Django 5.0.4 on 2024-04-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='Random',
        ),
    ]
