# Generated by Django 5.0.4 on 2024-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isInGame',
            field=models.BooleanField(default=False),
        ),
    ]
