# Generated by Django 5.0.4 on 2024-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_isingame'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
