# Generated by Django 5.0.4 on 2024-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_profil_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profil_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profil_photo'),
        ),
    ]
