# Generated by Django 5.0.4 on 2024-04-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_player_profil_photo'),
        ('accounts', '0003_player_point'),
    ]

    operations = [
    ]
