# Generated by Django 5.0.4 on 2024-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20240429_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'Player'},
        ),
        migrations.AddField(
            model_name='player',
            name='numberGame',
            field=models.IntegerField(default=0),
        ),
    ]
