# Generated by Django 5.0.4 on 2024-04-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_player_options_player_numbergame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='numberGame',
            new_name='numberGamePlay',
        ),
    ]
