# Generated by Django 3.1.7 on 2024-04-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_player_options'),
        ('accounts', '0006_rename_numbergame_player_numbergameplay'),
    ]

    operations = [
    ]
